version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm start
    depends_on:
      - database
    restart: always
  database:
    container_name: database
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=recordsservice
    env_file:
      - ./database/db.env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3036:3306"

